# Generated by Django 5.0.7 on 2024-08-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTHPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('channels', models.CharField(max_length=50)),
                ('validity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FiberPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=50)),
                ('validity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PostpaidPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=50)),
                ('validity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PrepaidPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=50)),
                ('validity', models.CharField(max_length=50)),
            ],
        ),
    ]
